name: Build and Push Rocky Linux 9.3 docker image to create local docs.rockylinux.org 
#
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: wsoyinka/local-rockylinux-docs
          ref: main 
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DH_USERNAME1 }}
          password: ${{ secrets.DH_PAT1 }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64/v8  -t ${{ secrets.DH_USERNAME1 }}/rockydocs:9.3 . --push
#       env:
#          DOCKERHUB_USERNAME: ${{ secrets.DH_USERNAME1 }}
#          DOCKERHUB_PASSWORD: ${{ secrets.DH_PAT1 }}
